apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lurus-www-tls
  namespace: lurus-www
spec:
  secretName: lurus-www-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - www.lurus.cn
