apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lurus-www
  namespace: lurus-www
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - www.lurus.cn
        - lurus.cn
      secretName: lurus-www-tls
  rules:
    - host: www.lurus.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lurus-www
                port:
                  number: 80
    - host: lurus.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lurus-www
                port:
                  number: 80
