apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lurus-www
  namespace: lurus-www
  labels:
    app: lurus-www
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.lurus.cn`) || Host(`lurus.cn`)
      kind: Rule
      services:
        - name: lurus-www
          port: 80
  tls:
    secretName: lurus-cn-wildcard-tls
