apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lurus-www

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/name: lurus-www
  app.kubernetes.io/part-of: lurus

images:
  - name: ghcr.io/hanmahong5-arch/lurus-www
    newTag: latest
