apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lurus-www-pdb
  namespace: lurus-www
  labels:
    app: lurus-www
    app.kubernetes.io/name: lurus-www
    app.kubernetes.io/part-of: lurus
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: lurus-www
